### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by iOS-Nishant** [Maximus-/class-dump-swift#1]
Hi,
Many thanks for creating this swift de-compiler. I am not able to find an instruction set about what are the commands? e.g. for Old Class dump (http://stevenygard.com/projects/class-dump/) one can use classdump <APP_FILE_NAME>. I have downloaded LLVM and compiled the project using a single "make" command.

**Comment by Maximus-** [comment]
This should do:
`./swift-dump` <binary> -o outputdir`

I'll make it more clear by putting a help menu in soon.

**Comment by iOS-Nishant** [comment]
Thanks.
